Modified debian/ directory to build the 0.10 as package

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -9,57 +9,99 @@
 # Uncomment this to turn on verbose mode.
 #export DH_VERBOSE=1
 
-export PYBUILD_DISABLE_python2=1
-
-%:
-	dh $@ --with python3,systemd --buildsystem pybuild
-
 DESTDIR=$(CURDIR)/debian/fail2ban
-PYVERSION=$(shell py3versions -dv)
 
-override_dh_clean:
-	rm -rf fail2ban.egg-info
-	-rm debian/fail2ban.init
-	dh_clean
-	: # auto generated
-	-rm bin/fail2ban-python
+configure: configure-stamp
+configure-stamp:
+	dh_testdir
+	touch configure-stamp
 
 override_dh_install:
-	rm -f $(DESTDIR)/usr/share/doc/fail2ban/README.Solaris
-	rm -f $(DESTDIR)/etc/fail2ban/paths-fedora.conf
-	rm -f $(DESTDIR)/etc/fail2ban/paths-freebsd.conf
-	rm -f $(DESTDIR)/etc/fail2ban/paths-osx.conf
-	: # Remove explicitely created /var/run/fail2ban
-	: # just to please lintian since init file will
-	: # take care about it anyways
-	rm -rf $(DESTDIR)/var/run/ $(DESTDIR)/run/
-	: # Install monit configuration
-	install -d $(DESTDIR)/etc/monit/monitrc.d
-	install -m 644 files/monit/fail2ban $(DESTDIR)/etc/monit/monitrc.d/fail2ban
-	: # Install bash completion
-	install -d $(DESTDIR)/etc/bash_completion.d
-	install -m 644 files/bash-completion $(DESTDIR)/etc/bash_completion.d/fail2ban
-	: # Install systemd files
-	install -d $(DESTDIR)/lib/systemd/system
-	install -d $(DESTDIR)/usr/lib/tmpfiles.d
-	install -m 644 files/fail2ban.service $(DESTDIR)/lib/systemd/system
-	install -m 644 files/fail2ban-tmpfiles.conf $(DESTDIR)/usr/lib/tmpfiles.d
-	install -d $(DESTDIR)/lib/systemd/system
-	: # Install default jail enabler
-	install -m 644 debian/debian-files/jail.d_defaults-debian.conf $(DESTDIR)/etc/fail2ban/jail.d/defaults-debian.conf
+	debian/presetup.py
 	dh_install
 
-override_dh_auto_test:
+override_dh_clean:
+	echo "Cleaning up..."
+	rm -f config/filter.d/ignorecommands/apache-fakegooglebotc
+	rm -f bin/fail2ban-python
+	dh_clean
+
+build:
+
+build-arch:
+
+build-indep:
+
+clean: clean-inits
+	dh_testdir
+	dh_testroot
+	rm -f  build-stamp configure-stamp
+	rm -rf build
+	# Does not hurt to ask distutils to do their duty
+	python setup.py clean
+	# Enforce removal of *.pyc files. Apparently dh_clean does
+	# not perform find on provided filename patterns.
+	find . -name \*.pyc -exec rm -f {} \;
+	rm -f config/filter.d/ignorecommands/apache-fakegooglebotc
+	rm -f bin/fail2ban-python
+	dh_clean
+
+install: build
+	dh_testdir
+	dh_testroot
+	dh_clean -k
+	dh_installdirs
+
+	# Install the package into debian/fail2ban.
+	python setup.py install --root=$(DESTDIR) --no-compile --install-layout=deb
+	# Install Debian shipped jail file in 1 piece (instead of patching
+	# the shipped one since there are too many changes)
+	install -m 644 debian/jail.conf $(DESTDIR)/etc/fail2ban
+	# Remove explicitely created /var/run/fail2ban
+	# just to please lintian since init file will
+	# take care about it anyways
+	rm -rf $(DESTDIR)/var/run/fail2ban
+	# Install bash completion
+	install -d $(DESTDIR)/etc/bash_completion.d
+	install -m 644 files/bash-completion $(DESTDIR)/etc/bash_completion.d/fail2ban
+
+	# Run tests
 ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
-	cd build && LC_ALL=C.UTF-8 FAIL2BAN_CONFIG_DIR="$(CURDIR)/config" PYTHONPATH="$(CURDIR)/.pybuild/pythonX.Y_$(PYVERSION)/build/" scripts-*/fail2ban-testcases --no-network
+	./fail2ban-testcases-all || :
+else
+	: # Skip unittests due to nocheck
 endif
 
-override_dh_installexamples:
-	dh_installexamples files/ipmasq-* files/nagios files/cacti
+#
+# Just to comply with policy 4.8
+binary-arch:
 
-override_dh_installinit:
-	cp -p files/debian-initd debian/fail2ban.init
+# Build architecture-independent files here.
+binary-indep: install
+	dh_testdir
+	dh_testroot
+	dh_installchangelogs ChangeLog
+	dh_installdocs
+	dh_installexamples config/jail.conf files/ipmasq-*
+	dh_installlogrotate
+	dh_python2 /usr/share/fail2ban
 	dh_installinit -- defaults 99
 
-override_dh_installman:
+	# perform swap of order of calls to init and pycentral (or even
+	# bleedingly new dh_python2) in prerm to close #422655 --
+	# python-cleanup section is cut and placed at the end of the file
+	# since .init script would trigger their compilation again
+	sed -i -e '/^#.*ed by dh_python2/,/# End auto/{H;d};$$G' \
+		debian/fail2ban.prerm.debhelper
+
 	dh_installman man/*.[15]
+	dh_link
+	dh_compress
+	dh_fixperms
+	dh_installdeb
+	dh_gencontrol
+	dh_md5sums
+	dh_builddeb
+
+binary: binary-indep
+.PHONY: build clean binary-indep binary-arch binary install configure copy-inits clean-inits
